development:
  user:       coban
  password:   password
  name:       coban_dev
  host:       127.0.0.1
  port:       3306
  migration:  ./dev

test_unit:
  user:       coban
  password:   password
  name:       coban_test_unit
  host:       127.0.0.1
  port:       3306
  migration:  ./test