version: '2'
services:
  test:
    command: bash -c "sleep 5 && go test ./... -v"
    build:
      context: src
      dockerfile: builds/test.docker
    volumes:
      - ./configurations:/etc/configurations
    depends_on:
      - api
    environment:
      DB_ENV: test_unit
      PORT: 5000
      API_IP: 192.168.99.100
      API_PORT: 9000

  api:
    environment:
      DB_ENV: test_unit
      PORT: 5000

  db:
    environment:
      DB_ENV: test_unit
      MYSQL_DATABASE: coban_test_unit
      MYSQL_USER: coban
      MYSQL_PASSWORD: password