api:
  dockerfile: builds/test.docker
  ports:
    - 9000:5000
  command: bash -c "sleep 5 && /go/bin/migrations && go test ./..."
  environment:
    DB_ENV: test_unit
    PORT: 5000
  links:
    - db

db:
  environment:
    DB_ENV: test_unit
    MYSQL_DATABASE: coban_test_unit
    MYSQL_USER: coban
    MYSQL_PASSWORD: password