api:
  build: ./api
  volumes:
    - ./configurations:/etc/configurations
#  links:
#    - db

#db:
#  build: ./mysql
#  ports:
#    - 3306:3306
#  environment:
#    MYSQL_ROOT_PASSWORD: root
#    MYSQL_DATABASE: coban_dev
#    MYSQL_USER: coban
#    MYSQL_PASSWORD: password