#FROM mysql:latest

#ADD ./my.cnf /etc/mysql/my.cnf

#RUN mkdir -p /go/src/coban/migrations
#COPY ./mysql/migrations /go/src/coban/migrations
#COPY ./configurations/environments.yml /go/src/coban/migrations

#WORKDIR /go/src/coban/migrations

#RUN go-wrapper download
#RUN go-wrapper install
#RUN go-wrapper run

#ENV DB_ENV development

#EXPOSE 3306